sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${SKY_DB_HOST:localhost}
    port: ${SKY_DB_PORT:3306}
    database: ${SKY_DB_NAME:sky_take_out}
    username: ${SKY_DB_USERNAME:root}
    password: ${SKY_DB_PASSWORD:}
  local-file:
    upload-path: ${SKY_UPLOAD_PATH:./uploads}
    access-path: /images
